package main

import (
	"context"
	"flag"
	"fmt"
	"log"
	"sort"
	"time"

	"github.com/PagerDuty/go-pagerduty"
	"github.com/nlopes/slack"
)

const (
	START_DATE    = 20
	HOUR_TO_CHECK = 22
)

var (
	scheduleIDs = []string{
		"PL1PQV0", // Kaas-cloud On-Call Schedule
		"P253Q7G", // Kaas-onprem On-Call Schedule
		"PP96MB8", // platform On-Call Schedule
	}

	pagerdutyAuthToken string
	slackKey           string
)

func init() {
	flag.StringVar(&pagerdutyAuthToken, "pagerduty-auth-token", "", "Auth token for PagerDuty")
	flag.StringVar(&slackKey, "slack-key", "", "API key for Slack")
}

// getDates takes a year, month, hour, and start date (e.g: the 20th),
// and returns time.Times at that year, month, and hour for each day in that month.
// e.g: 2021, 5, 22, 20 -> [(2021, 5, 20, 22), (2021, 5, 21, 22), ..., (2021, 6, 19, 22)]
func getDates(year int, month time.Month, hour int, startDate int) ([]time.Time, error) {
	times := []time.Time{
		time.Date(year, month, startDate, hour, 0, 0, 0, time.UTC),
	}

	for {
		times = append(times, times[len(times)-1].AddDate(0, 0, 1))

		last := times[len(times)-1]
		if last.Month() == month+1 && last.Day() == startDate-1 {
			break
		}
	}

	return times, nil
}

func getOncaller(client *pagerduty.Client, scheduleID string, date time.Time) (string, error) {
	schedule, err := client.GetScheduleWithContext(context.Background(), scheduleID, pagerduty.GetScheduleOptions{
		Since: date.Format(time.RFC3339),
	})
	if err != nil {
		return "", err
	}

	name := schedule.FinalSchedule.RenderedScheduleEntries[0].User.Summary

	return name, nil
}

func printSummary(client *slack.Client, shifts map[string]int) error {
	names := []string{}
	for name := range shifts {
		names = append(names, name)
	}
	sort.Strings(names)

	attachment := slack.Attachment{
		Footer: "Generated by https://github.com/giantswarm/oncall-shift-reporter",
	}
	for _, name := range names {
		if name == "" {
			continue
		}

		attachment.Fields = append(attachment.Fields, slack.AttachmentField{
			Value: fmt.Sprintf("%v: %v", name, shifts[name]),
			Short: true,
		})
	}

	oneMonth, _ := time.ParseDuration("24h")
	oneMonth = oneMonth * 31
	if _, _, err := client.PostMessage(
		"#noise-shift-count",
		slack.MsgOptionAsUser(true),
		slack.MsgOptionText(
			fmt.Sprintf("Area oncall shift counts (%v of %v to %v of %v)", START_DATE, time.Now().Add((-oneMonth)).Month(), START_DATE-1, time.Now().Month()),
			false,
		),
		slack.MsgOptionAttachments(attachment),
	); err != nil {
		return err
	}

	return nil
}

func main() {
	flag.Parse()

	if pagerdutyAuthToken == "" {
		log.Fatalf("pagerduty auth token cannot be empty")
	}
	if slackKey == "" {
		log.Fatalf("slack key cannot be empty")
	}

	pagerdutyClient := pagerduty.NewClient(pagerdutyAuthToken)

	slackClient := slack.New(slackKey)

	times, err := getDates(time.Now().Year(), time.Now().Month()-1, HOUR_TO_CHECK, START_DATE)
	if err != nil {
		log.Fatalf("%v", err)
	}

	shifts := map[string]int{}

	for _, schedule := range scheduleIDs {
		for _, t := range times {
			oncaller, err := getOncaller(pagerdutyClient, schedule, t)
			if err != nil {
				log.Fatalf("%v", err)
			}

			shifts[oncaller]++

			time.Sleep(1 * time.Second) // To avoid rate limiting
		}
	}

	fmt.Println(shifts)

	if err := printSummary(slackClient, shifts); err != nil {
		log.Fatalf("%v", err)
	}
}
